#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <signal.h>

#define CONFIG_FILE "/etc/trinkey/config"
#define PID_FILE    "/tmp/trinkey.pid"

static void print_usage(const char *prog)
{
    fprintf(stderr,
            "usage: %s [options]\n"
            "options:\n"
            "  -m <mode>      set LED mode (static, blink, breath)\n"
            "  -i \"R G B\"     set idle colour  (e.g. \"255 0 0\")\n"
            "  -t \"R G B\"     set touch colour (e.g. \"0 255 0\")\n"
            "  -h             show this help\n",
            prog);
}

/* Read the daemon PID from the pidfile and send SIGHUP so it reloads
 * the config. Logs a warning (not an error) if the daemon is not running,
 * since the config update is still valid.
 */
static void notify_daemon(void)
{
    FILE *f = fopen(PID_FILE, "r");
    if (!f) {
        fprintf(stderr, "warning: daemon pidfile not found (%s), "
        "config saved but daemon not notified\n", PID_FILE);
        return;
    }

    int pid;
    int ok = (fscanf(f, "%d", &pid) == 1);
    fclose(f);

    if (!ok) {
        fprintf(stderr, "warning: could not read PID from %s\n", PID_FILE);
        return;
    }

    if (kill(pid, SIGHUP) != 0)
        perror("warning: could not signal daemon");
}

int main(int argc, char *argv[])
{
    char *new_mode  = NULL;
    char *new_idle  = NULL;
    char *new_touch = NULL;

    int opt;
    while ((opt = getopt(argc, argv, "m:i:t:h")) != -1) {
        switch (opt) {
            case 'm': new_mode  = optarg; break;
            case 'i': new_idle  = optarg; break;
            case 't': new_touch = optarg; break;
            case 'h': print_usage(argv[0]); return 0;
            default:  print_usage(argv[0]); return 1;
        }
    }

    if (!new_mode && !new_idle && !new_touch) {
        fprintf(stderr, "error: no options provided\n");
        print_usage(argv[0]);
        return 1;
    }

    /* Current values; overwritten by whatever is in the config file,
     * then selectively replaced by the user's arguments.
     */
    char mode[64]        = "static";
    char idle_color[64]  = "255 0 0";
    char touch_color[64] = "0 255 0";

    /* Read existing config so unspecified keys are preserved. */
    FILE *f = fopen(CONFIG_FILE, "r");
    if (f) {
        char line[256];
        while (fgets(line, sizeof(line), f)) {
            char key[64], val[64];
            if (sscanf(line, "%63[^=]=%63[^\n]", key, val) != 2)
                continue;
            if (strcmp(key, "mode") == 0)
                strncpy(mode, val, sizeof(mode) - 1);
            else if (strcmp(key, "idle_color") == 0)
                strncpy(idle_color, val, sizeof(idle_color) - 1);
            else if (strcmp(key, "touch_color") == 0)
                strncpy(touch_color, val, sizeof(touch_color) - 1);
        }
        fclose(f);
    }

    /* Apply user-supplied changes. */
    if (new_mode)  strncpy(mode,        new_mode,  sizeof(mode)        - 1);
    if (new_idle)  strncpy(idle_color,  new_idle,  sizeof(idle_color)  - 1);
    if (new_touch) strncpy(touch_color, new_touch, sizeof(touch_color) - 1);

    /* Write updated config. */
    f = fopen(CONFIG_FILE, "w");
    if (!f) {
        perror("error: cannot write config file (try sudo)");
        return 1;
    }
    fprintf(f, "# generated by trinkey-ctl\n");
    fprintf(f, "mode=%s\n",        mode);
    fprintf(f, "idle_color=%s\n",  idle_color);
    fprintf(f, "touch_color=%s\n", touch_color);
    fclose(f);

    printf("config written to %s\n", CONFIG_FILE);
    notify_daemon();
    return 0;
}
