#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <signal.h>

#define CONFIG_FILE "/etc/trinkey/config"

static void print_usage(const char *prog)
{
    fprintf(stderr,
            "usage: %s [options]\n"
            "options:\n"
            "  -m <mode>      set LED mode (static, blink, breath)\n"
            "  -i \"R G B\"     set idle colour  (e.g. \"255 0 0\")\n"
            "  -t \"R G B\"     set touch colour (e.g. \"0 255 0\")\n"
            "  -h             show this help\n",
            prog);
}

static void notify_daemon(void)
{
    FILE *f = fopen("/run/trinkey/trinkey.pid", "r");
    if (!f) {
        fprintf(stderr, "warning: daemon not running\n");
        return;
    }
    int pid;
    int ok = (fscanf(f, "%d", &pid) == 1);
    fclose(f);
    if (!ok) {
        fprintf(stderr, "warning: could not read PID\n");
        return;
    }
    if (kill(pid, SIGHUP) != 0)
        perror("warning: could not signal daemon");
}

// Check wether the parameters given by the user are valid
static int valid_mode(const char *m)
{
    return strcmp(m, "static") == 0 ||
    strcmp(m, "blink")  == 0 ||
    strcmp(m, "breath") == 0;
}

static int valid_color(const char *s)
{
    int r, g, b;
    if (sscanf(s, "%d %d %d", &r, &g, &b) != 3)
        return 0;
    return r >= 0 && r <= 255 &&
    g >= 0 && g <= 255 &&
    b >= 0 && b <= 255;
}


int main(int argc, char *argv[])
{
    char *new_mode  = NULL;
    char *new_idle  = NULL;
    char *new_touch = NULL;

    int opt;
    while ((opt = getopt(argc, argv, "m:i:t:h")) != -1) {
        switch (opt) {
            case 'm': new_mode  = optarg; break;
            case 'i': new_idle  = optarg; break;
            case 't': new_touch = optarg; break;
            case 'h': print_usage(argv[0]); return 0;
            default:  print_usage(argv[0]); return 1;
        }
    }

    if (new_mode && !valid_mode(new_mode)) {
        fprintf(stderr, "error: invalid mode '%s' (use static, blink, breath)\n", new_mode);
        return 1;
    }
    if (new_idle && !valid_color(new_idle)) {
        fprintf(stderr, "error: invalid color '%s' (use \"R G B\" with values 0-255)\n", new_idle);
        return 1;
    }
    if (new_touch && !valid_color(new_touch)) {
        fprintf(stderr, "error: invalid color '%s'\n", new_touch);
        return 1;
    }

    /* Current values; overwritten by whatever is in the config file,
     * then selectively replaced by the user's arguments.
     */
    char mode[64]        = "static";
    char idle_color[64]  = "255 0 0";
    char touch_color[64] = "0 255 0";

    /* Read existing config so unspecified keys are preserved. */
    FILE *f = fopen(CONFIG_FILE, "r");
    if (f) {
        char line[256];
        while (fgets(line, sizeof(line), f)) {
            char key[64], val[64];
            if (sscanf(line, "%63[^=]=%63[^\n]", key, val) != 2)
                continue;
            if (strcmp(key, "mode") == 0)
                strncpy(mode, val, sizeof(mode) - 1);
            else if (strcmp(key, "idle_color") == 0)
                strncpy(idle_color, val, sizeof(idle_color) - 1);
            else if (strcmp(key, "touch_color") == 0)
                strncpy(touch_color, val, sizeof(touch_color) - 1);
        }
        fclose(f);
    }

    /* Apply user-supplied changes. */
    if (new_mode)  strncpy(mode,        new_mode,  sizeof(mode)        - 1);
    if (new_idle)  strncpy(idle_color,  new_idle,  sizeof(idle_color)  - 1);
    if (new_touch) strncpy(touch_color, new_touch, sizeof(touch_color) - 1);

    /* Write updated config. */
    f = fopen(CONFIG_FILE, "w");
    if (!f) {
        perror("error: cannot write config file (try sudo)");
        return 1;
    }
    fprintf(f, "# generated by trinkey-ctl\n");
    fprintf(f, "mode=%s\n",        mode);
    fprintf(f, "idle_color=%s\n",  idle_color);
    fprintf(f, "touch_color=%s\n", touch_color);
    fclose(f);

    printf("config written to %s\n", CONFIG_FILE);
    notify_daemon();
    return 0;
}
